#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
##
## BSPWM config file for Archcraft

## General ---------------------------------------------------#
source "$HOME/.zshenv"

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

## Current theme ---------------------------------------------#

## Load current theme files to get colors for bspwm
source "$BSPDIR"/themes/current.bash

## Wallpaper
CURRENT_WALLPAPER=$(find ~/Pictures/wallpapers/ | sort -R | tail -1)

## Get the colors from theme file
FOREGROUND="$foreground"
BACKGROUND="$background"
CURSOR="$cursor"
BLACK="$color0"
RED="$color1"
GREEN="$color2"
YELLOW="$color3"
BLUE="$color4"
MAGENTA="$color5"
CYAN="$color6"
WHITE="$color7"
ALTBLACK="$color8"
ALTRED="$color9"
ALTGREEN="$color10"
ALTYELLOW="$color11"
ALTBLUE="$color12"
ALTMAGENTA="$color13"
ALTCYAN="$color14"
ALTWHITE="$color15"

## Bspwm appearance
CURRENT_BORDER='2'
CURRENT_GAP='0'
CURRENT_SRATIO='0.50'

## Configurations --------------------------------------------#
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer false
bspc config pointer_follows_monitor
bspc config ignore_ewmh_focus true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

## Always Floating Apps
declare -a floating=(kitty-float pinentry-gnome3)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating layer=above; done

# Start floating windows off to the right hand side
bspc config external_rules_command ~/.config/bspwm/bin/bspwinpos

## Always Fullscreen Apps
declare -a fullscreen=(kitty-full)
for i in ${fullscreen[@]}; do
   bspc rule -a $i state=fullscreen; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
feh --no-fehbg --bg-fill "$CURRENT_WALLPAPER"

# Sensible DAS and capslock switch
xset r rate 300 50
setxkbmap -option caps:escape
setxkbmap -option terminate:ctrl_alt_bksp

# Mice bindings
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Start bspwm scripts
bspworkspaceupdate
bspcolors
bspbar
bspcomp
bspdunst
[[ -z "$(pgrep bspmonitor)" ]] && bspmonitor &
[[ -z "$(pgrep bspfloat)" ]] && bspfloat &

# Launch default programs
[[ -z "$(pgrep redshift)" ]] && redshift -l 45:-73 &

if [[ -z "$(pgrep --full 'firefox -P personal')" ]]; then
  bspc rule -a firefox desktop='^2'; gtk-launch firefox; bspc rule -r firefox &
fi

if [[ -z "$(pgrep --full 'firefox -P work')" ]]; then
  bspc rule -a firefox-work desktop='^5'; gtk-launch firefox-work; bspc rule -r firefox-work &
fi
