#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
##
## BSPWM config file for Archcraft

## General ---------------------------------------------------#
source "$HOME/.zshenv"

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

## Current theme ---------------------------------------------#

## Load current theme files to get colors for bspwm
source "$BSPDIR"/themes/current.bash

## Get the wallpaper from theme file
CURRENT_WALLPAPER="$wallpaper"

## Get the colors from theme file
FOREGROUND="$foreground"
BACKGROUND="$background"
CURSOR="$cursor"
BLACK="$color0"
RED="$color1"
GREEN="$color2"
YELLOW="$color3"
BLUE="$color4"
MAGENTA="$color5"
CYAN="$color6"
WHITE="$color7"
ALTBLACK="$color8"
ALTRED="$color9"
ALTGREEN="$color10"
ALTYELLOW="$color11"
ALTBLUE="$color12"
ALTMAGENTA="$color13"
ALTCYAN="$color14"
ALTWHITE="$color15"

## Bspwm appearance
CURRENT_BORDER='2'
CURRENT_GAP='0'
CURRENT_SRATIO='0.50'

## Configurations --------------------------------------------#
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer false
bspc config pointer_follows_monitor
bspc config ignore_ewmh_focus true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
# bspc rule -a kitty desktop='^1'
bspc rule -a Xfce4-terminal desktop='^1'

## 2 > web (always open web browser on workspace-2)
bspc rule -a firefox desktop='^2'

## 3 > files (always open file manager on workspace-3)
declare -a files=(Pcmanfm)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3'; done

## 4 > code (always open editors on workspace-4)
declare -a code=(Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4'; done

## 5 > office and docs (always open office/doc apps on workspace-5)
declare -a office=(firefox-work Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5'; done

## 6 > communication (always open communication apps on workspace-6)
declare -a comm=(Thunderbird TelegramDesktop Hexchat discord Signal)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6'; done

## 7 > media (always open media apps on workspace-7)
declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=tiled; done

## 8 > system (always open system apps on workspace-8)
bspc rule -a 'VirtualBox Manager' desktop='^8'
bspc rule -a 'virt-manager' desktop='^8'
bspc rule -a GParted desktop='^8'
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=tiled; done

## Always Floating Apps
declare -a floating=(kitty-float Pcmanfm Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor pinentry-gnome3)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating layer=above; done

# Start floating windows off to the right hand side
bspc config external_rules_command ~/.config/bspwm/bin/bspwinpos

## Always Fullscreen Apps
declare -a fullscreen=(kitty-full)
for i in ${fullscreen[@]}; do
   bspc rule -a $i state=fullscreen; done

## Always Pseudo Apps
declare -a pseudo=(Discord discord Signal)
for i in ${pseudo[@]}; do
   bspc rule -a $i state=pseudo; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
feh --no-fehbg --bg-fill "$CURRENT_WALLPAPER"

# Sensible DAS and capslock switch
xset r rate 300 50
setxkbmap -option caps:escape
setxkbmap -option terminate:ctrl_alt_bksp

# Mice bindings
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Start bspwm scripts
bspworkspaceupdate
bspcolors
bspbar
bspcomp
bspdunst
[[ -z "$(pgrep bspmonitor)" ]] && bspmonitor &
[[ -z "$(pgrep bspfloat)" ]] && bspfloat &

# Launch default programs
[[ -z "$(pgrep --full 'firefox -P personal')" ]] && gtk-launch firefox &
[[ -z "$(pgrep --full 'firefox -P work')" ]] && gtk-launch firefox-work &
[[ -z "$(pgrep redshift)" ]] && redshift -l 45:-73 &
